### PR TITLE
Consolodate command-line-introduction into resources

### PR DESCRIPTION
**Pull request by smacz42**
This PR is a proposal to reduce the number of repositories the OSUOSC officers and alumni maintain by merging command-line-introduction into the club resources repo.

### CODE REVIEW

**Comment by moore3071** [comment]
I could see this being merged into resources, but I'm thinking only a link to this should be included unless we plan on major restructuring of this repo.

**Comment by smacz42** [comment]
To clarify, you would be in favor of only adding a link to https://github.com/OSUOSC/command-line-introduction into the README here?

**Comment by moore3071** [comment]
Correct. For now that's all I'd be comfortable with.

**Comment by Nefari0uss** [comment]
@moore3071 Thoughts about adding my Git presentation as a resource? And my Introduction to Linux talk I gave?

**Comment by moore3071** [comment]
It's doable @Nefari0uss. Mind adding that as an issue, and we can discuss it there.

**Comment by Nefari0uss** [comment]
I'll do that.

**Pull request merged**
